name: bloc_error_handler
description: "Bloc event handler for emitting new error states and reducing boiler plate"
version: 0.0.4
homepage: https://github.com/yourusername/bloc_error_handler

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.1
  grpc: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
 